version: '3.7'

services:
    mysql_container:
        image: mysql:5.7
        container_name: store_mysql
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            #- mysql_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=store
            - MYSQL_USER=store
            - MYSQL_PASSWORD=store
            - MYSQL_ROOT_PASSWORD=store
        # network_mode: host
#volumes:
#    mysql_data:
